config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: "pages#profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :skills do
    resources :experiences, only: [:index, :create]
    resources :bookings, only: [:create] do
      get "update_status", to: 'bookings#update_status'
    end
  end
  resources :experiences, only: [:edit, :update]
  resources :bookings, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :chatrooms, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" >
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-trainup">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_blanc_rm.png", class:"logo" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%# <li class="nav-item active"> %>
          <%# <%= link_to "Home", "#", class: "nav-link" %>
        <%# </li> %>
        <li class="nav-item">
        <!--<button type="button" class="">Light</button> -->

          <%= link_to "Réserve un cours", skills_path, class: "btn btn-light rounded-pill btn-space reserve" %>
        </li>
        <li class="nav-item">
          <%= link_to "Deviens coach",  new_skill_path, class: "nav-link btn-space" %>
        </li>
        <% if Message.where(chatroom: current_user.chatrooms).where.not(user: current_user, read: true).any? %>
          <li class="nav-item">
            <p><%= link_to '<i class="fas fa-circle"></i>'.html_safe, chatrooms_path %></p>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/brivdarcy", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", profile_path, class: "dropdown-item" %>
            <%= link_to "Messages", chatrooms_path, class: "dropdown-item"  if current_user.chatrooms.any? %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-flex justify-content-center">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
           <%= link_to "Inscription", new_user_registration_path, class: "nav-link active" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>