config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: "pages#profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :skills do
    resources :experiences, only: [:index, :create]
    resources :bookings, only: [:create] do
      get "update_status", to: 'bookings#update_status'
    end
  end
  resources :experiences, only: [:edit, :update]
  resources :bookings, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :chatrooms, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end
end

app/views/pages/home.html.erb
<div class="banner" style='background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path "banner.png" %>)'>

	<div class="container">
  <!--   <h1>Améliore tes compétences <span id="textFade">techniques</span> !</h1> -->
	<div class="title-trainup">
		Train Up
	</div>
	<div>
		<%= form_tag skills_path, class: "search d-flex", method: :get do %>
		  <div class="barre">
		  	<%= text_field_tag :query,
		    params[:query],
		    class: "form-control",
		    placeholder: "Coach escrime Paris"
		  	%>
			</div>
			<div>
		  		<%= submit_tag "Recherche", class: "btn btn-green" %>
			</div>
		<% end %>
	</div>
		<%#= link_to skills_path do %>
			<!-- <div class="btn-green">Trouve ton coach</div> -->
		<%# end %>
    	<h1>Améliore tes compétences <span class="fade-in" id="banner-typed-text">techniques</span></h1>
	</div>

</div>

<div class="container">
	<div class="home-cards d-flex justify-content-between">
		<div class="home-card">
	    	<%= image_tag "home-run.png", class:"home-card-image" %>
	    	<h2>Tous les coachs</h2>
	     </div>
		<div class="home-card">
	    	<%= image_tag "home-fusee.png", class:"home-card-image" %>
	    	<h2>Réservation rapide</h2>
	    </div>
		<div class="home-card">
	    	<%= image_tag "home-calandar.png", class:"home-card-image" %>
	    	<h2>À la carte</h2>
	    </div>
	</div>
</div>
<div class="avantages">
    <div class="avantages-text">
      <p>Vous cherchez à améliorer <span class="text-in-green">vos performances sportives</span> dans un sport en particulier ?
         TrainUp sélectionne pour vous <span class="text-in-green">des coachs professionnels</span> qui vous permettront de progresser aussi bien sur le <span class="text-in-green">plan technique, physique ou mental</span>.
       </p>
    </div>
    <div class="image">
      <%= image_tag "logo_vert.png", alt: "logo", class:"logo-text" %>
    </div>
    <div class="avatantages-text2">
         <p>Réservez en quelques clics le professionel de votre choix.
         Grâce au <span class="text-in-green">chat</span>, vous pouvez échanger avec votre coach avant la séance, pour exposer vos objectifs et bénéficier
         d'une <span class="text-in-green">séance complètement personnalisée</span>.
       </p>
    </div>

</div>

app/views/pages/profile.html.erb
<% content_for :meta_title, "TrainUp: ton profil" %>
<% content_for :meta_description, "Retrouve sur ton tableau de bord toutes tes réserations" %>
<% content_for :meta_image, cl_image_path("banner.png") %>

<!-- page client -->
<% if current_user.skills.empty? %>
  <%= image_tag "runner.png", alt: "runner", class: "runner" %>
  <%= image_tag "runnerbis.png", alt: "runner", class: "runnerbis" %>
  <div class="container-profile">
    <div class="profile-identity">
      <div class="profile-image">
        <%= cl_image_tag @current_user.photo.key, id: "show-profile", crop: :thumb, gravity: :face %>
      </div>
      <div class="profile-infos">
        <p><span class="bold">Nom : </span><%= current_user.last_name.capitalize %></p>
        <p><span class="bold">Prénom : </span><%= current_user.first_name.capitalize %></p>
        <p><i class="fas fa-birthday-cake"></i> <%= current_user.birth_date.strftime("%e/%m/%Y") %></p>
        <p><i class="fas fa-venus-mars"></i> <%= current_user.sex %></p>
        <p><i class="fas fa-map-marker-alt"></i> <%= current_user.address %></p>
        <p><i class="fas fa-at"></i> <%= current_user.email %></p>
        <br>
        <%= link_to "Modifier", edit_user_registration_path, class: "btn-green client", id: "user-modif" %>
      </div>
    </div>

    <div class="profile-tableau">
      <h3 class="titre"><i class="far fa-clipboard"></i> Tableau de bord</h3>
      <hr>
      <div class="profile-resas">
        <div class="resas-en-cours">
          <h3>Réservations en cours<i class="fas fa-caret-down"></i></h3>
          <% if current_user.bookings.live.any? %>
              <% current_user.bookings.live.each do |booking| %>
                <div class="reservations-en-cours">
                  <% if booking.status == "en attente" %>
                    <div class="btn-attente"><%= booking.status %></div>
                  <% else %>
                    <div class="btn-ok"><%= booking.status %></div>
                  <% end %>
                  <p><span class="bold"><%= booking.skill.user.first_name.capitalize %> <%= booking.skill.user.last_name.capitalize %></span></p>
                  <p class="italique"><%= booking.skill.name %></p>
                  <p class="italique"><% booking.skill.experiences.each do |experience| %>
                    (<%= experience.sport.name %>)
                    <% end %></p>
                  <p class="calendar"><i class="far fa-calendar-alt"></i> <%= booking.start_date.to_date.strftime("%e/%m/%Y")%></p>
                  <p><i class="far fa-clock"></i> <%= booking.start_hour %>h à <%= booking.end_hour %>h</p>
                  <hr>
                  <div class="link-client">
                    <p>Total : <%= booking.total_price %> €</p>
                  </div>
                  <div class="boutons">
                    <% if Chatroom.find_by_users(current_user, booking.skill.user) %>
                      <div class="chat-btn-one">
                        <%= link_to "Chat avec le coach", chatroom_path(Chatroom.find_by_users(current_user, booking.skill.user)), class: "btn-green"  %>
                        <% if policy(booking).destroy? %>
                          <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete, data: {confirm: "Es-tu sûr d'annuler cette réservation ?"} %>
                        <% end %>
                      </div>
                    <% else %>
                      <div class="chat-btn-two">
                        <%= simple_form_for(Chatroom.new) do |f| %>
                        <%= f.input :user_id, input_html: {value: booking.skill.user.id}, as: :hidden %>
                        <%= f.button :submit, "Chat avec le coach", class: "btn-green" %>
                        <% end %>
                        <% if policy(booking).destroy? %>
                        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete, data: {confirm: "Es-tu sûr d'annuler cette réservation ?"} %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
          <% else %>
              <div class="reservations-en-cours">
                <p>Tu n'as aucune réservation en cours...</p>
              </div>
          <% end %>
        </div>
        <div class="resas-passees">
          <h3>Réservations passées<i class="fas fa-caret-down"></i></h3>
          <% if current_user.bookings.past.any? %>
              <% current_user.bookings.past.each do |booking| %>
                <div class="reservations-past">
                  <p><span class="bold"><%= booking.skill.user.first_name.capitalize %> <%= booking.skill.user.last_name.capitalize %></span></p>
                  <p class="italique"><%= booking.skill.name %></p>
                      <p class="italique"><% booking.skill.experiences.each do |experience| %>
                        (<%= experience.sport.name %>)
                      <% end %></p>
                  <p class="calendar"><i class="far fa-calendar-alt"></i> <%= booking.start_date.to_date.strftime("%e/%m/%Y") %></p>
                  <p><i class="far fa-clock"></i> <%= booking.start_hour %>h à <%= booking.end_hour %>h</p>
                  <hr>
                  <p>Total : <%= booking.total_price %> €</p>

                  <div class="link-review">
                  <% if policy(booking.reviews).create? %>

                  <%= link_to "Laisse un commentaire", skill_path(booking.skill, anchor: "comment"), data: { turbolinks: 'false' }, class: "btn-green" %>
                  <% end %>
                  </div>
                </div>
              <% end %>
          <% else %>
            <div class="reservations-past">
              <p>Tu n'as aucune réservation passée...</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<!-- page coach -->
<% else %>
  <div class="container-profile-coach">
    <div class="profile-tableau-client">
      <h3 class="titre"><i class="far fa-clipboard"></i> Tableau de bord client</h3>
      <hr>
      <div class="coach-as-user-resas">
        <h3>Réservations en cours<i class="fas fa-caret-down"></i></h3>
        <% if current_user.bookings.live.any? %>
            <% current_user.bookings.live.each do |booking| %>
              <div class="reservations-coach-as-user">
                <p class="bold"><%= booking.skill.user.first_name.capitalize %> <%= booking.skill.user.last_name.capitalize %></p>
                <p class="italique"><%= booking.skill.name %></p>
                <p class="italique"> <% booking.skill.experiences.each do |experience| %>
                      (<%= experience.sport.name %>)
                    <% end %></p>
                <p class="calendar"><i class="far fa-calendar-alt"></i> <%= booking.start_date.to_date.strftime("%e/%m/%Y") %></p>
                <p><i class="far fa-clock"></i> <%= booking.start_hour %>h à <%= booking.end_hour %>h</p>
                <hr>
                <p>Total : <%= booking.total_price %> €</p>
                <div class="boutons">
                    <% if Chatroom.find_by_users(current_user, booking.skill.user) %>
                      <div class="chat-btn-one">
                        <%= link_to "Chat avec le coach", chatroom_path(Chatroom.find_by_users(current_user, booking.skill.user)), class: "btn-green"  %>
                        <% if policy(booking).destroy? %>
                          <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete, data: {confirm: "Es-tu sûr d'annuler cette réservation ?"} %>
                        <% end %>
                      </div>
                    <% else %>
                      <div class="chat-btn-two">
                        <%= simple_form_for(Chatroom.new) do |f| %>
                        <%= f.input :user_id, input_html: {value: booking.skill.user.id}, as: :hidden %>
                        <%= f.button :submit, "Chat avec le coach", class: "btn-green" %>
                        <% end %>
                        <% if policy(booking).destroy? %>
                        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete, data: {confirm: "Es-tu sûr d'annuler cette réservation ?"} %>
                        <% end %>
                      </div>
                    <% end %>
                </div>
              </div>
            <% end %>
        <% else %>
          <div class="reservations-coach-as-user">
            <p>Tu n'as pas de réservations en cours...</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="profile-identity">
      <div class="profile-image-coach">
        <%= cl_image_tag @current_user.photo.key, id: "show-profile", crop: :thumb, gravity: :face %>
      </div>
      <div class="profile-infos-coach">
        <p><span class="bold">Nom : </span><%= current_user.last_name.capitalize %></p>
        <p><span class="bold">Prénom : </span><%= current_user.first_name.capitalize %></p>
        <p><i class="fas fa-birthday-cake"></i> <%= current_user.birth_date.strftime("%e/%m/%Y") %></p>
        <p><i class="fas fa-map-marker-alt"></i> <%= current_user.address %></p>
        <p><i class="fas fa-at"></i> <%= current_user.email %></p>
        <br>
        <%= link_to "Edit", edit_user_registration_path, class: "btn-green client", id: "user-modif" %>
        <hr class="hr-coach">
      </div>
      <div class="coach-seance">
          <% current_user.skills.each do |skill|  %>
          <h5 class="card-title"><%= skill.name %></h5>
            <p><span class="bold">Description : </span><%= skill.description%></p>
            <p><i class="fas fa-map-marker-alt"></i> <%= skill.location%></p>
              <% skill.experiences.each do |experience| %>
                <p class="price-info"><i class="fas fa-tags logo-price"></i>  <%= experience.price %> €/h</p>
                <br>
                  <%= link_to "Edit", edit_skill_path(skill), class: "btn-green modifier-btn" %>
              <% end %>
          <% end %>
          <hr class="hr-coach">
      </div>
      <div class="coach-experience">
        <% current_user.skills.each do |skill| %>
        <h5 class="card-title">Ton expérience</h5>
          <% skill.experiences.each do |experience|  %>
            <p><span class="bold">Ton sport :</span> <%= experience.sport.name %></p>
            <p><span class="bold">Années d'expérience :</span> <%= experience.years %> ans</p>
            <p><span class="bold">Spécialité :</span> <%= experience.specialty %></p>
            <br>
              <%= link_to "Edit", edit_experience_path(experience), class: "btn-green modifier-btn" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="profile-tableau">
      <h3 class="titre"><i class="far fa-clipboard"></i> Tableau de bord Pro</h3>
      <hr>
      <div class="profile-resas">
        <div class="resas-en-cours">
          <h3>Réservations en cours<i class="fas fa-caret-down"></i></h3>
          <% if current_user.received_bookings.live.any? %>
            <% current_user.received_bookings.live.each do |received_booking| %>
              <div class="reservations-en-cours-coach">
                <p><span class="bold">Ton client :</span> <%= received_booking.user.first_name.capitalize %> <%= received_booking.user.last_name.capitalize %></p>
                <p><i class="far fa-calendar-alt"></i> <%= received_booking.start_date.to_date.strftime("%e/%m/%Y")%></p>
                <p><i class="far fa-clock"></i> <%= received_booking.start_hour %>h à <%= received_booking.end_hour %>h</p>
                <hr>
                <p>Totals : <%= received_booking.total_price %> €</p>
                <% if policy(received_booking).destroy? %>
                  <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete, data: {confirm: "Es-tu sûr d'annuler cette réservation ?"}, class: "btn-green" %>
                <% end %>
                <% if policy(received_booking).update_status? %>
                  <% if received_booking.status != "accepté" %>
                    <%= link_to 'accepter', skill_booking_update_status_path(received_booking.skill, received_booking), method: :get, class: "btn-green" %>
                  <% else %>
                  <p>Accepté</p>
                  <% end %>
                <% end %>
              </div>

            <% end %>
          <% else %>
            <div class="reservations-en-cours-coach">
              <p>Tu n'as pas de réservation actuellement...</p>
            </div>
          <% end %>
        </div>
        <div class="reviews">
          <h3>Commentaires clients<i class="fas fa-caret-down"></i></h3>
          <% if current_user.reviews.any? %>
            <div class="reviews-coach">
              <% current_user.reviews.last(3).each do |review| %>
                <p><%= review.user.first_name.capitalize %> <%= review.user.last_name.first %></p>
                <p><%= review.content %></p>
                <div class="rating">
                  <%= review.rating.times do %>
                        <i class="fas fa-star"></i>
                  <% end %>
                </div>
                <% end %>
            </div>
          <% else %>
            <div class="reviews-coach">
              <p>Pas de commentaires pour le moment...</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>